stages:
  train:
    cmd: python train.py
    deps:
      - train.py
      - params.yaml
      - mlops_equipo_63/__init__.py
      - mlops_equipo_63/Configuration.py
      - mlops_equipo_63/load_and_preparation.py
      - mlops_equipo_63/Optuna_Study.py
      - mlops_equipo_63/Retrain_and_Evaluate.py
      - mlops_equipo_63/Split_and_Dummy.py
      - mlops_equipo_63/mlflow_utils.py
      - ${data.raw_path}
    outs:
      - ${data.processed_dir}/dataset_processed.csv
      - models/final_model.pkl
    metrics:
      - reports/metrics.json:
          cache: false
    plots:
      - reports/confusion_matrix.png:
          cache: false
      - reports/feature_importance.png:
          cache: false   